apiVersion: v1
kind: Service
metadata:
  name: {{ include "fableous.fullname" . }}-fe
  labels:
    {{- include "fableous.labels" . | nindent 4 }}
    tier: fe
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fableous.selectorLabels" . | nindent 4 }}
    tier: fe

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fableous.fullname" . }}-be
  labels:
    {{- include "fableous.labels" . | nindent 4 }}
    tier: be
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fableous.selectorLabels" . | nindent 4 }}
    tier: be
