name: Build

on: push

jobs:
  lint-fe:
    name: Lint fableous-fe
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fableous-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm install
      - name: eslint
        run: npm run lint
  build-fe:
    name: Build fableous-fe
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: fableous-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-fe
          path: |
            fableous-fe/dist/
  lint-be:
    name: Lint fableous-be
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: fableous-be
  build-be:
    name: Build fableous-be
    runs-on: Ubuntu-20.04
    container: daystram/go-builder:1.16
    defaults:
      run:
        working-directory: fableous-be
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: go mod tidy
      - name: Build
        run: go build -a -o app .
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-be
          path: |
            fableous-be/app
