name: Build:Backend

on:
  workflow_dispatch:
  push:
    paths:
      - "fableous-be/**"
      - "proto/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fableous-be
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Generate Files
        run: |
          make -C .. be
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: fableous-be
          skip-go-installation: true
          skip-pkg-cache: true
  build:
    name: Build
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: fableous-be
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Generate Files
        run: |
          make -C .. be
      - name: Install Dependencies
        run: go mod tidy
      - name: Build
        run: go build -a -o app .
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-be
          path: |
            fableous-be/app
