name: Build:Frontend

on:
  workflow_dispatch:
  push:
    paths:
      - "fableous-fe/**"
      - "proto/**"
      - ".github/**"
      - "Makefile"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fableous-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Generate Files
        run: make -C .. fe
      - name: Install Dependencies
        run: yarn
      - name: eslint
        run: yarn lint
  build:
    name: Build
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: fableous-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Generate Files
        run: make -C .. fe
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-fe
          path: |
            fableous-fe/build/
