name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  image:
    name: Publish Image
    environment: Production
    runs-on: Ubuntu-20.04
    env:
      APPLICATION: fableous
    strategy:
      matrix:
        service: [be, fe]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Provide Env File
        run: |
          echo "${{ secrets.FE_ENV_FILE }}" > ${{ env.APPLICATION }}-${{ matrix.service }}/.env.production
          echo "REACT_APP_VERSION=${{ env.RELEASE_VERSION }}" >> ${{ env.APPLICATION }}-${{ matrix.service }}/.env.production
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.APPLICATION }}-${{ matrix.service }}
          platforms: linux/amd64
          tags: |
            daystram/${{ env.APPLICATION }}:${{ matrix.service }}
            daystram/${{ env.APPLICATION }}:${{ matrix.service }}-${{ env.RELEASE_VERSION }}
          push: true
